#! /bin/sh

sxhkd &

bspc monitor -d term web code music irssi VI VII

bspc config border_width         2
bspc config window_gap          15

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Firefox desktop='^2' follow=true
bspc rule -a Emacs desktop='^3' follow=true
#bspc rule -a mpv state=floating
#bspc rule -a Screenkey manage=off
bspc rule -a feh state=floating focus=on
bspc rule -a URxvt:ncmpcpp desktop='^4' follow=on
bspc rule -a URxvt:floating state=floating

bspc desktop web --layout monocle

# Autostart
/home/m1311/.config/bspwm/autostart &
